groups:
  - name: node_alerts
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        annotations:
          summary: "High CPU usage detected on instance {{ $labels.instance }}"
          description: "CPU usage is above 80% for 2 minutes"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
        for: 2m
        annotations:
          summary: "High memory usage detected on instance {{ $labels.instance }}"
          description: "Memory usage is above 80% for 2 minutes"

      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 20
        for: 2m
        annotations:
          summary: "Low disk space detected on instance {{ $labels.instance }}"
          description: "Disk space is below 20% for 2 minutes"

  - name: Network_Alerts
    rules:
      - alert: High latency HTTP
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox probe slow HTTP (instance {{ $labels.instance }})
          description: "HTTP request took more than 1s\n on instance {{ $labels.instance }}  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: High latency ping
        expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Server has slow ping (instance {{ $labels.instance }})
          description: "Ping took more than 1s\n  on instance {{ $labels.instance }} VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: HTTP Status Error
        expr: avg_over_time(probe_http_status_code[1m]) != 200
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: HTTP status  (instance {{ $labels.instance }})
          description: "HTTP status code not 200\n on instance {{ $labels.instance }}  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: High TCP connection
        expr: sum(node_netstat_Tcp_CurrEstab) > 300
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: TCP connection status  (instance {{ $labels.instance }})
          description: "Experiencing high TCP demand  on instance {{ $labels.instance }} "



  - name: Ceph alerts
    rules:
      - alert: CephState
        expr: ceph_health_status != 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Ceph State (instance {{ $labels.instance }})
          description: "Ceph instance unhealthy\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: CephMonitorClockSkew
        expr: abs(ceph_monitor_clock_skew_seconds) > 0.2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Ceph monitor clock skew (instance {{ $labels.instance }})
          description: "Ceph monitor clock skew detected. Please check ntp and hardware clock settings\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"



      - alert: CephMonitorLowSpace
        expr: ceph_monitor_avail_percent < 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Ceph monitor low space (instance {{ $labels.instance }})
          description: "Ceph monitor storage is low.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: CephOsdDown
        expr: ceph_osd_up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Ceph OSD Down (instance {{ $labels.instance }})
          description: "Ceph Object Storage Daemon Down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: CephHighOsdLatency
        expr: ceph_osd_perf_apply_latency_seconds > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Ceph high OSD latency (instance {{ $labels.instance }})
          description: "Ceph Object Storage Daemon latency is high. Please check if it doesn't stuck in weird state.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"



      - alert: CephOsdLowSpace
        expr: ceph_osd_utilization > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Ceph OSD low space (instance {{ $labels.instance }})
          description: "Ceph Object Storage Daemon is going out of space. Please add more disks.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"



      - alert: CephOsdReweighted
        expr: ceph_osd_weight < 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Ceph OSD reweighted (instance {{ $labels.instance }})
          description: "Ceph Object Storage Daemon takes too much time to resize.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"




      - alert: CephPgDown
        expr: ceph_pg_down > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Ceph PG down (instance {{ $labels.instance }})
          description: "Some Ceph placement groups are down. Please ensure that all the data are available.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"





      - alert: CephPgIncomplete
        expr: ceph_pg_incomplete > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Ceph PG incomplete (instance {{ $labels.instance }})
          description: "Some Ceph placement groups are incomplete. Please ensure that all the data are available.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"





      - alert: CephPgInconsistent
        expr: ceph_pg_inconsistent > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Ceph PG inconsistent (instance {{ $labels.instance }})
          description: "Some Ceph placement groups are inconsistent. Data is available but inconsistent across nodes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"




      - alert: CephPgActivationLong
        expr: ceph_pg_activating > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Ceph PG activation long (instance {{ $labels.instance }})
          description: "Some Ceph placement groups are too long to activate.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"





      - alert: CephPgBackfillFull
        expr: ceph_pg_backfill_toofull > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Ceph PG backfill full (instance {{ $labels.instance }})
          description: "Some Ceph placement groups are located on full Object Storage Daemon on cluster. Those PGs can be unavailable shortly. Please check OSDs, change weight or reconfigure CRUSH rules.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"




      - alert: CephPgUnavailable
        expr: ceph_pg_total - ceph_pg_active > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Ceph PG unavailable (instance {{ $labels.instance }})
          description: "Some Ceph placement groups are unavailable.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  - name: System_Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "The instance has been down for more than 5 minutes."

      - alert: HighLoadAverage5m
        expr: node_load5 > 5
        for: 5m
        annotations:
          summary: "High load average detected on {{ $labels.instance }}"
          description: "The load average (last 5 minutes) is above 5 for 5 minutes."

      - alert: RapidDiskWritesIncrease
        expr: predict_linear(node_disk_written_bytes_total[1h], 4 * 3600) > 5e+09
        for: 10m
        annotations:
          summary: "Rapid increase in disk writes on {{ $labels.instance }}"
          description: "The rate of increase in disk writes suggests the disk might be full within the next 4 hours."

      - alert: RapidNetworkTrafficIncrease
        expr: predict_linear(node_network_receive_bytes_total[1h], 4 * 3600) > 1e+09
        for: 10m
        annotations:
          summary: "Rapid increase in network traffic on {{ $labels.instance }}"
          description: "The rate of increase in network traffic suggests there might be an unusual network activity in the next 4 hours."

      - alert: InstanceTimeDrift
        expr: abs(node_timex_offset_seconds) > 0.05
        for: 5m
        annotations:
          summary: "Time drift detected on {{ $labels.instance }}"
          description: "The instance's time offset from the NTP server is more than 50ms for 5 minutes."


