---
- name: Check for connectivity
  ping:
    data: alive


- name: Get the private IP address
  shell:
    cmd: ip --json a s | jq -r '.[] | if .ifname | startswith("en") then .addr_info[] | if .family == "inet" then .local else empty end else empty end' | head -n 1
  register: result

- name: Print out the initial status of the cluster
  debug:
    var: result



- name: Initiaze the ceph cluster on the first mon
  shell:
    cmd: "cephadm bootstrap --mon-ip {{ result.stdout }} --cluster-network 10.0.0.0/8 --ssh-user root --skip-mon-network "


- name: Get out the initial status of the cluster
  shell:
    cmd: "ceph status"
  register: ceph_status


- name: Adding the public network to the mons
  shell:
    cmd: ceph config set mon public_network 0.0.0.0/0


- name: Print out the initial status of the cluster
  debug:
    var: ceph_status


- name: Fetch the ceph.pub from the remote host
  fetch:
    src: /etc/ceph/ceph.pub
    dest: /root/ceph.pub
    flat: yes
