---
- name: check connectivity
  ping:
    data: alive


- name: Install required packages for a ceph node
  apt:
    update_cache: yes
    pkg:
      - pip
      - cephadm
      - ceph-common
    state: present


- name: Copy /etc/hosts file
  template:
    src: files/etchost.yaml
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'