---
- name: Check for connectivity
  ping:
    data: alive


- name: Copy the pub key to every node
  blockinfile:
    path: /root/.ssh/authorized_keys
    block: "{{ lookup('file', '/root/ceph.pub') }}"



- name: Copy the scrip to add hosts to the server
  copy:
    src: files/adding_hosts.sh
    dest: /root/adding_hosts.sh
    mode: 0700
    owner: root
    group: root


- name: Make the script executable
  shell:
    cmd: chmod +x /root/adding_hosts.sh


- name: Run the script and add the hosts
  shell:
    cmd: /bin/bash /root/adding_hosts.sh


- name: Get out the initial status of the cluster
  shell:
    cmd: "ceph status"
  register: ceph_status


- name: Print out the initial status of the cluster
  debug:
    var: ceph_status


- name: Add the additional disks to the cluster
  shell:
    cmd: |
      ceph orch daemon add osd osd-1:/dev/sdb
      ceph orch daemon add osd osd-2:/dev/sdb
      ceph orch daemon add osd osd-3:/dev/sdb


- name: Get out the initial status of the cluster
  shell:
    cmd: "ceph status"
  register: ceph_status


- name: Print out the initial status of the cluster
  debug:
    var: ceph_status




- name: Enable functionality of RGWs on the cluster
  shell:
    cmd: ceph orch apply rgw kangrgw --placement="2 label:rgw" --port=8585



- name: Get out the initial status of the cluster
  shell:
    cmd: "ceph status"
  register: ceph_status


- name: Print out the initial status of the cluster
  debug:
    var: ceph_status


