---
- name: check connectivity
  ping:
    data: alive


- name: update and upgrade system
  apt:
    update_cache: yes
    upgrade: dist


- name: install some base packages
  apt:
    pkg:
      - net-tools
      - xz-utils
      - bmon
      - curl
      - tcpdump
      - vim
      - apt-transport-https
      - ca-certificates
      - curl
      - python3
      - jq
      - resolvconf
      - python3-pip
    state: present



