---
- name: check connectivity
  ping:
    data: alive

- name: update and upgrade system
  apt:
    update_cache: yes
    upgrade: dist

- name: Create the required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0744
    owner: root
    group: root
  with_items:
    - /root/monitoring
    - /root/monitoring/Grafana
    - /root/monitoring/Prometheus
    - /root/monitoring/Alertmanager
    - /root/monitoring/Dashboards
    - /root/monitoring/Grafana/provisioning


- name: Copy alertmanager files
  copy:
    src: files/Alertmanager/alertmanager.yaml
    dest: /root/monitoring/Alertmanager/


- name: Copy Dashboard files
  copy:
    src: files/Dashboards/overview.json
    dest: /root/monitoring/Dashboards/


- name: Copy Grafana files
  copy:
    src: files/grafana.ini
    dest: /root/monitoring/Grafana


- name: Copy Prometheus files
  copy:
    src: files/Prometheus/"{{ item }}"
    dest: /root/monitoring/Prometheus/
  with_items:
    - alert_rules.yaml
    - prometheus.yaml




- name: pull the required images
  docker_image:
    name: "{{ item}}"
    source: pull
  with_items:
    - prom/node-exporter:latest
    - victoriametrics/vmagent:latest
    - victoriametrics/victoria-metrics:latest
    - grafana/grafana:latest
    - victoriametrics/vmalert:latest
    - prom/alertmanager:latest


- name: Create the required volumes
  docker_volume:
    volume_name: "{{ item }}"
    state: present
  with_items:
    - vmagentdata
    - vmdata
    - grafana_data


- name: Run the container for Node Exporter
  docker_container:
    name: node-exporter
    image: prom/node-exporter:latest
    restart_policy: unless-stopped
    state: started
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    published_ports:
      - 9100:9100
    network_mode: host

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro



- name: Run the container for Vmagent
  docker_container:
    name: vmagent
    image: victoriametrics/vmagent:latest
    restart_policy: always
    published_ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - /root/monitoring/Prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
      - "-promscrape.config.strictParse=false"



- name: Run the container for Victoria metrics
  docker_container:
    name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    restart_policy: always
    published_ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"




- name: Run the container for Grafana
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    restart_policy: always
    published_ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - /root/monitoring/Grafana/:/etc/grafana/
      - /root/monitoring/Grafana/provisioning:/etc/grafana/provisioning
      - /root/monitoring/Dashboards/:/var/lib/grafana/dashboards/





- name: Run the container for Vmalert
  docker_container:
    name: vmalert
    image: victoriametrics/vmalert:latest
    restart_policy: always
    published_ports:
      - 8880:8880
    volumes:
      - vmagentdata:/vmagentdata
      - /root/monitoring/Prometheus/alert_rules.yaml:/etc/prometheus/alert_rules.yaml
      - /root/monitoring/Prometheus/:/etc/prometheus/

    command:
      - "--datasource.url=http://victoriametrics:8428/"
      - "--remoteRead.url=http://victoriametrics:8428/"
      - "--remoteWrite.url=http://victoriametrics:8428/"
      - "--notifier.url=http://alertmanager:9093/"
      - "--rule=/etc/alerts/*.yml"

#      # display source of alerts in grafana
#      - "--external.url=http://127.0.0.1:3000" #grafana outside container
#      # when copypaste the line be aware of '$$' for escaping in '$expr'
#      - '--external.alert.source=explore?orgId=1&left={"datasource":"VictoriaMetrics","queries":[{"expr":{{$$expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"now-1h","to":"now"}}'




- name: Run the container for Alertmanager
  docker_container:
    name: alertmanager
    image: prom/alertmanager:latest
    restart_policy: always
    published_ports:
      - 9093:9093
    volumes:
      - vmagentdata:/vmagentdata
      - /root/monitoring/Alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'







