---
- name: setting up Ceph object storage cluster
  hosts: all
  become: true
  tasks:
    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        - $PWD/roles/OS_Tuning
        - $PWD/roles/Instaling_Docker
        - $PWD/roles/Ceph_Pre_Setup


    - name: Init the cluster
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Initialize_cluster
      when: mode == 'mon' and init_cluster == 'true'


    - name: Copy the pub key to every node
      blockinfile:
        path: /root/.ssh/authorized_keys
        block: "{{ lookup('file', '/root/ceph.pub') }}"


    - name: Add hosts to the ceph cluster
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Add_Hosts_To_Ceph
      when: mode == 'mon' and init_cluster == 'true'


    - name: Add exporters
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Exporters/Ceph_Exporter
        - $PWD/roles/Exporters/Node_Exporter
        #- $PWD/roles/RGW_Exporter


    - name: Create a client
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Create_Client
      when: mode == 'mon' and init_cluster == 'true'



