---
- name: setting up Ceph object storage cluster
  hosts: all
  become: true
  tasks:

    - name: Include variables
      include_vars: "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        - $PWD/roles/OS_Tuning
        - $PWD/roles/Instaling_Docker
        - $PWD/roles/Ceph_Pre_Setup

    - name: Init the cluster
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Initialize_cluster
      when: mode == 'mon' and init_cluster == 'true'


    - name: Copy the pub key to every node
      blockinfile:
        path: /root/.ssh/authorized_keys
        block: "{{ lookup('file', '/root/ceph.pub') }}"


    - name: Add hosts to the ceph cluster
      include_role:
        name: "{{ item }}"
      include_vars:
        - $PWD/group_vars/all.yaml
      with_items:
        - $PWD/roles/Add_Hosts_To_Ceph
      when: mode == 'mon' and init_cluster == 'true'



    - name: Deploy Node exporter on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Exporters/Node_Exporter


    - name: First disable the default node exporter of ceph
      shell:
        cmd: ceph orch stop node-exporter
      when: mode == 'mon'
      
    - name: Remove  the default node exporter of ceph
      shell:
        cmd: ceph orch rm node-exporter
      when: mode == 'mon'


    - name: Ceph monitoring
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Exporters/Ceph_Exporter
      when: mode != 'monitoring'

#    - name: Monitoring User bucket on RGW
#      include_role:
#        name: " {{ item }}"
#      with_items:
#        - $PWD/roles/RGW_Exporter
#      when: mode == 'rgw'

    - name: Create a client
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Create_Client
      when: mode == 'mon' and init_cluster == 'true'

    - name: Set up the monitoring stack
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Victoria_Metrics
      when: mode == 'monitoring'



