{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_exporter_build_info,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy node $node ",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Used $node",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Root FS Used $node",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Basic $node",
   "type": "stat",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic $node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\", job=\"$job\" }[$__rate_interval])*8\n",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])*8\n",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Connections $node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dynamic is \"-1\")"
    }
   ]
  },
  {
   "title": "TCP Errors $node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutRsts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutRsts - Segments sent with RST flag"
    }
   ]
  },
  {
   "title": "UDP Errors $node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  }
 ]
}